name: Notify Discord on Push

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: Ilshidur/action-discord@master
        with:
          args: "🚀 A new commit has been pushed to the repository!"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
