name: Notify Discord on Push

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: Ilshidur/action-discord@master
        with:
          args: |
            **[${{ github.repository }}:${{ github.ref_name }}] ${{ github.event.commits && github.event.commits.length || 1 }} new commit(s)**

            [\`${{ github.event.head_commit.id }}\`.slice(0, 7)] ${{ github.event.head_commit.message }} - ${{ github.actor }}
            <${{ github.event.head_commit.url }}>
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
